#!/usr/bin/env python3
"""
Swiss Tax Calculator Generator for City of Zürich
Creates an Excel spreadsheet for personal tax calculations (2025 tax year)

Tailored for: Single employed person in City of Zürich
Author: Generated by Claude Code
Date: December 2025
"""

from openpyxl import Workbook
from openpyxl.styles import Font, PatternFill, Alignment, Border, Side
from openpyxl.utils import get_column_letter
from openpyxl.worksheet.datavalidation import DataValidation

# Color scheme
COLOR_INPUT = "B4C7E7"  # Light blue - user inputs
COLOR_CALC = "C6E0B4"   # Light green - calculated fields
COLOR_RESULT = "FFE699"  # Light yellow - results
COLOR_HEADER = "4472C4"  # Dark blue - headers

def create_tax_calculator():
    """Create the complete tax calculator workbook"""
    wb = Workbook()

    # Create sheets
    ws_calc = wb.active
    ws_calc.title = "Tax Calculator"
    ws_ref = wb.create_sheet("Tax Brackets Reference")
    ws_tips = wb.create_sheet("Optimization Tips")
    ws_instructions = wb.create_sheet("Instructions")

    # Build each sheet
    create_calculator_sheet(ws_calc)
    create_reference_sheet(ws_ref)
    create_tips_sheet(ws_tips)
    create_instructions_sheet(ws_instructions)

    # Save the workbook
    filename = "Swiss_Tax_Calculator_2025_Zurich.xlsx"
    wb.save(filename)
    print(f"[OK] Tax calculator created successfully: {filename}")
    print(f"[OK] Location: Desktop/Python_Scripts/{filename}")
    print(f"\nOpen the file in Excel or Google Sheets to start calculating your taxes!")

    return filename


def create_calculator_sheet(ws):
    """Create the main tax calculator sheet"""

    # Set column widths
    ws.column_dimensions['A'].width = 35
    ws.column_dimensions['B'].width = 18
    ws.column_dimensions['C'].width = 30
    ws.column_dimensions['D'].width = 18
    ws.column_dimensions['E'].width = 30

    row = 1

    # Title
    ws.merge_cells(f'A{row}:E{row}')
    ws[f'A{row}'] = 'SWISS TAX CALCULATOR 2025 - CITY OF ZÜRICH'
    ws[f'A{row}'].font = Font(bold=True, size=16, color="FFFFFF")
    ws[f'A{row}'].fill = PatternFill(start_color=COLOR_HEADER, fill_type="solid")
    ws[f'A{row}'].alignment = Alignment(horizontal='center', vertical='center')
    ws.row_dimensions[row].height = 30
    row += 1

    ws.merge_cells(f'A{row}:E{row}')
    ws[f'A{row}'] = 'Single Employed Person | Federal + Cantonal + Municipal + Wealth Tax'
    ws[f'A{row}'].font = Font(italic=True, size=10)
    ws[f'A{row}'].alignment = Alignment(horizontal='center')
    row += 2

    # ====================
    # SECTION A: INCOME
    # ====================
    row = create_section_header(ws, row, "A. INCOME & GROSS SALARY")

    # Gross salary
    ws[f'A{row}'] = 'Gross Annual Salary (CHF)'
    ws[f'B{row}'] = 0
    apply_input_style(ws[f'B{row}'])
    ws[f'C{row}'] = 'Enter your total annual salary'
    ws[f'C{row}'].font = Font(italic=True, size=9)
    row += 1

    # Social security (auto-calculated)
    ws[f'A{row}'] = 'AHV/IV/EO (5.3% of salary)'
    ws[f'B{row}'] = f'=B{row-1}*0.053'
    apply_calc_style(ws[f'B{row}'])
    ws[f'B{row}'].number_format = '#,##0.00'
    ws[f'C{row}'] = 'Auto-calculated (employee portion)'
    ws[f'C{row}'].font = Font(italic=True, size=9, color="666666")
    row += 1

    ws[f'A{row}'] = 'Unemployment ALV (1.1% up to CHF 148,200)'
    salary_row = row - 2
    ws[f'B{row}'] = f'=MIN(B{salary_row},148200)*0.011'
    apply_calc_style(ws[f'B{row}'])
    ws[f'B{row}'].number_format = '#,##0.00'
    ws[f'C{row}'] = 'Auto-calculated (capped at CHF 148,200)'
    ws[f'C{row}'].font = Font(italic=True, size=9, color="666666")
    row += 1

    # Other income
    ws[f'A{row}'] = 'Other Employment Income'
    ws[f'B{row}'] = 0
    apply_input_style(ws[f'B{row}'])
    ws[f'C{row}'] = 'Bonuses, commissions, etc.'
    row += 1

    ws[f'A{row}'] = 'Investment Income (Dividends/Interest)'
    ws[f'B{row}'] = 0
    apply_input_style(ws[f'B{row}'])
    ws[f'C{row}'] = 'Taxable investment income'
    row += 1

    ws[f'A{row}'] = 'Rental Income'
    ws[f'B{row}'] = 0
    apply_input_style(ws[f'B{row}'])
    ws[f'C{row}'] = 'Net rental income (if applicable)'
    row += 1

    ws[f'A{row}'] = 'Other Income'
    ws[f'B{row}'] = 0
    apply_input_style(ws[f'B{row}'])
    ws[f'C{row}'] = 'Any other taxable income'
    row += 1

    # Total gross income
    gross_income_row = row
    ws[f'A{row}'] = 'TOTAL GROSS INCOME'
    income_start = salary_row
    income_end = row - 1
    ws[f'B{row}'] = f'=SUM(B{income_start}:B{income_end})'
    apply_result_style(ws[f'B{row}'])
    ws[f'B{row}'].font = Font(bold=True, size=12)
    ws[f'B{row}'].number_format = '#,##0.00'
    row += 2

    # ====================
    # SECTION B: DEDUCTIONS
    # ====================
    deductions_start_row = row
    row = create_section_header(ws, row, "B. DEDUCTIONS")

    # Pillar 3a
    ws[f'A{row}'] = 'Pillar 3a Contributions'
    ws[f'B{row}'] = 0
    apply_input_style(ws[f'B{row}'])
    ws[f'C{row}'] = 'Max CHF 7,258 for 2025'
    ws[f'C{row}'].font = Font(size=9, color="FF0000")
    # Add validation
    dv = DataValidation(type="decimal", operator="lessThanOrEqual", formula1="7258")
    dv.error = "Pillar 3a maximum is CHF 7,258 for 2025"
    dv.errorTitle = "Invalid Amount"
    ws.add_data_validation(dv)
    dv.add(f'B{row}')
    pillar3a_row = row
    row += 1

    ws[f'A{row}'] = 'Pillar 2 Buyback'
    ws[f'B{row}'] = 0
    apply_input_style(ws[f'B{row}'])
    ws[f'C{row}'] = 'Voluntary pension buyback'
    row += 1

    # Insurance
    ws[f'A{row}'] = 'Health Insurance Premiums (Krankenversicherung)'
    ws[f'B{row}'] = 0
    apply_input_style(ws[f'B{row}'])
    ws[f'C{row}'] = 'Annual health insurance cost'
    row += 1

    ws[f'A{row}'] = 'Other Insurance (Life, Accident, etc.)'
    ws[f'B{row}'] = 0
    apply_input_style(ws[f'B{row}'])
    ws[f'C{row}'] = 'Max CHF 3,700 (federal)'
    row += 1

    # Professional expenses
    ws[f'A{row}'] = 'Commuting Costs'
    ws[f'B{row}'] = 0
    apply_input_style(ws[f'B{row}'])
    ws[f'C{row}'] = 'Public transport or mileage'
    row += 1

    ws[f'A{row}'] = 'Working Days (for meal deductions)'
    ws[f'B{row}'] = 220
    apply_input_style(ws[f'B{row}'])
    ws[f'C{row}'] = 'Typical: 220 days/year'
    working_days_row = row
    row += 1

    ws[f'A{row}'] = 'Meal Expense Rate (CHF per day)'
    ws[f'B{row}'] = 15
    apply_input_style(ws[f'B{row}'])
    ws[f'C{row}'] = '15 = no canteen, 7.50 = with canteen'
    meal_rate_row = row
    row += 1

    ws[f'A{row}'] = 'Total Meal Expenses'
    ws[f'B{row}'] = f'=B{working_days_row}*B{meal_rate_row}'
    apply_calc_style(ws[f'B{row}'])
    ws[f'B{row}'].number_format = '#,##0.00'
    ws[f'C{row}'] = 'Auto-calculated'
    ws[f'C{row}'].font = Font(italic=True, size=9, color="666666")
    meal_total_row = row
    row += 1

    ws[f'A{row}'] = 'Professional Expenses (3% flat-rate)'
    ws[f'B{row}'] = f'=MIN(B{gross_income_row}*0.03, 4000)'
    apply_calc_style(ws[f'B{row}'])
    ws[f'B{row}'].number_format = '#,##0.00'
    ws[f'C{row}'] = 'Max CHF 4,000 (federal)'
    ws[f'C{row}'].font = Font(italic=True, size=9, color="666666")
    row += 1

    ws[f'A{row}'] = 'Education/Training Costs'
    ws[f'B{row}'] = 0
    apply_input_style(ws[f'B{row}'])
    ws[f'C{row}'] = 'Max CHF 13,000 (post-secondary)'
    row += 1

    # Real estate
    ws[f'A{row}'] = 'Mortgage Interest'
    ws[f'B{row}'] = 0
    apply_input_style(ws[f'B{row}'])
    ws[f'C{row}'] = 'Until 2028 (Eigenmietwert reform)'
    row += 1

    ws[f'A{row}'] = 'Property Maintenance Costs'
    ws[f'B{row}'] = 0
    apply_input_style(ws[f'B{row}'])
    ws[f'C{row}'] = 'Until 2028 (Eigenmietwert reform)'
    row += 1

    # Other deductions
    ws[f'A{row}'] = 'Donations to Charities'
    ws[f'B{row}'] = 0
    apply_input_style(ws[f'B{row}'])
    ws[f'C{row}'] = 'Min CHF 100, Max 20% of income'
    row += 1

    ws[f'A{row}'] = 'Political Donations'
    ws[f'B{row}'] = 0
    apply_input_style(ws[f'B{row}'])
    ws[f'C{row}'] = 'Max CHF 10,600'
    row += 1

    ws[f'A{row}'] = 'Loan Interest (Credit Cards, Personal Loans)'
    ws[f'B{row}'] = 0
    apply_input_style(ws[f'B{row}'])
    ws[f'C{row}'] = 'All loan interest is deductible'
    row += 1

    ws[f'A{row}'] = 'Childcare Costs'
    ws[f'B{row}'] = 0
    apply_input_style(ws[f'B{row}'])
    ws[f'C{row}'] = 'Max CHF 25,800 (federal)'
    row += 1

    ws[f'A{row}'] = 'Other Deductions'
    ws[f'B{row}'] = 0
    apply_input_style(ws[f'B{row}'])
    ws[f'C{row}'] = 'Alimony, etc.'
    deductions_end_row = row
    row += 1

    # Social security deductions
    ws[f'A{row}'] = 'Social Security (AHV/IV/EO + ALV)'
    ahv_row = salary_row + 1
    alv_row = salary_row + 2
    ws[f'B{row}'] = f'=B{ahv_row}+B{alv_row}'
    apply_calc_style(ws[f'B{row}'])
    ws[f'B{row}'].number_format = '#,##0.00'
    ws[f'C{row}'] = 'Auto-calculated from salary'
    ws[f'C{row}'].font = Font(italic=True, size=9, color="666666")
    social_security_row = row
    row += 1

    # Total deductions
    total_deductions_row = row
    ws[f'A{row}'] = 'TOTAL DEDUCTIONS'
    ws[f'B{row}'] = f'=SUM(B{deductions_start_row+1}:B{deductions_end_row})+B{social_security_row}'
    apply_result_style(ws[f'B{row}'])
    ws[f'B{row}'].font = Font(bold=True, size=12)
    ws[f'B{row}'].number_format = '#,##0.00'
    row += 2

    # ====================
    # SECTION C: TAXABLE INCOME
    # ====================
    row = create_section_header(ws, row, "C. TAXABLE INCOME")

    ws[f'A{row}'] = 'Gross Income'
    ws[f'B{row}'] = f'=B{gross_income_row}'
    apply_calc_style(ws[f'B{row}'])
    ws[f'B{row}'].number_format = '#,##0.00'
    row += 1

    ws[f'A{row}'] = 'Minus: Total Deductions'
    ws[f'B{row}'] = f'=-B{total_deductions_row}'
    apply_calc_style(ws[f'B{row}'])
    ws[f'B{row}'].number_format = '#,##0.00'
    row += 1

    taxable_income_row = row
    ws[f'A{row}'] = 'TAXABLE INCOME'
    ws[f'B{row}'] = f'=B{gross_income_row}-B{total_deductions_row}'
    apply_result_style(ws[f'B{row}'])
    ws[f'B{row}'].font = Font(bold=True, size=14, color="FF0000")
    ws[f'B{row}'].number_format = '#,##0.00'
    row += 2

    # ====================
    # SECTION D: TAX CALCULATIONS
    # ====================
    row = create_section_header(ws, row, "D. TAX CALCULATIONS")

    # Federal tax
    ws[f'A{row}'] = 'Federal Direct Tax'
    federal_tax_row = row
    # Complex federal tax formula (simplified for key brackets)
    income_cell = f'B{taxable_income_row}'
    federal_tax_formula = f'''=IF({income_cell}<=15200,0,
IF({income_cell}<=32800,({income_cell}-15000)*0.0077,
IF({income_cell}<=42900,137.05+({income_cell}-32800)*0.0088,
IF({income_cell}<=57200,225.90+({income_cell}-42900)*0.0264,
IF({income_cell}<=75300,603.40+({income_cell}-57200)*0.0297,
IF({income_cell}<=103400,1140.90+({income_cell}-75300)*0.0594,
IF({income_cell}<=134600,2811.30+({income_cell}-103400)*0.066,
IF({income_cell}<=176000,4870.50+({income_cell}-134600)*0.088,
IF({income_cell}<=755200,8513.70+({income_cell}-176000)*0.11,
90198.90+({income_cell}-755200)*0.115)))))))'''

    ws[f'B{row}'] = federal_tax_formula
    apply_result_style(ws[f'B{row}'])
    ws[f'B{row}'].number_format = '#,##0.00'
    ws[f'C{row}'] = 'Based on Article 36 DBG (Single)'
    ws[f'C{row}'].font = Font(italic=True, size=9)
    row += 1

    ws[f'A{row}'] = 'Federal Tax Rate (%)'
    ws[f'B{row}'] = f'=IF(B{taxable_income_row}>0,B{federal_tax_row}/B{taxable_income_row}*100,0)'
    apply_calc_style(ws[f'B{row}'])
    ws[f'B{row}'].number_format = '0.00"%"'
    row += 2

    # Cantonal tax (Zürich) - simplified estimate
    ws[f'A{row}'] = 'Zürich Cantonal Tax (Estimated)'
    cantonal_tax_row = row
    # Zürich cantonal tax is approximately 2.5x federal tax (simplified)
    ws[f'B{row}'] = f'=B{federal_tax_row}*2.5'
    apply_result_style(ws[f'B{row}'])
    ws[f'B{row}'].number_format = '#,##0.00'
    ws[f'C{row}'] = 'Approximate rate (2.5x federal)'
    ws[f'C{row}'].font = Font(italic=True, size=9, color="FF6600")
    row += 1

    ws[f'A{row}'] = 'Cantonal Tax Rate (%)'
    ws[f'B{row}'] = f'=IF(B{taxable_income_row}>0,B{cantonal_tax_row}/B{taxable_income_row}*100,0)'
    apply_calc_style(ws[f'B{row}'])
    ws[f'B{row}'].number_format = '0.00"%"'
    row += 2

    # Municipal tax (City of Zürich)
    ws[f'A{row}'] = 'City of Zürich Municipal Tax'
    municipal_tax_row = row
    ws[f'B{row}'] = f'=B{cantonal_tax_row}*1.19'
    apply_result_style(ws[f'B{row}'])
    ws[f'B{row}'].number_format = '#,##0.00'
    ws[f'C{row}'] = '119% multiplier for City of Zürich'
    ws[f'C{row}'].font = Font(italic=True, size=9)
    row += 1

    ws[f'A{row}'] = 'Municipal Tax Rate (%)'
    ws[f'B{row}'] = f'=IF(B{taxable_income_row}>0,B{municipal_tax_row}/B{taxable_income_row}*100,0)'
    apply_calc_style(ws[f'B{row}'])
    ws[f'B{row}'].number_format = '0.00"%"'
    row += 2

    # ====================
    # SECTION E: WEALTH TAX
    # ====================
    row = create_section_header(ws, row, "E. WEALTH TAX")

    ws[f'A{row}'] = 'Securities/Investments (Dec 31 value)'
    ws[f'B{row}'] = 0
    apply_input_style(ws[f'B{row}'])
    securities_row = row
    row += 1

    ws[f'A{row}'] = 'Bank Accounts/Cash'
    ws[f'B{row}'] = 0
    apply_input_style(ws[f'B{row}'])
    cash_row = row
    row += 1

    ws[f'A{row}'] = 'Real Estate Value (Tax Value)'
    ws[f'B{row}'] = 0
    apply_input_style(ws[f'B{row}'])
    real_estate_row = row
    row += 1

    ws[f'A{row}'] = 'Other Assets'
    ws[f'B{row}'] = 0
    apply_input_style(ws[f'B{row}'])
    other_assets_row = row
    row += 1

    ws[f'A{row}'] = 'Minus: Debts (Mortgages, Loans)'
    ws[f'B{row}'] = 0
    apply_input_style(ws[f'B{row}'])
    debts_row = row
    row += 1

    ws[f'A{row}'] = 'Gross Wealth'
    gross_wealth_row = row
    ws[f'B{row}'] = f'=B{securities_row}+B{cash_row}+B{real_estate_row}+B{other_assets_row}'
    apply_calc_style(ws[f'B{row}'])
    ws[f'B{row}'].number_format = '#,##0.00'
    row += 1

    ws[f'A{row}'] = 'Net Wealth'
    net_wealth_row = row
    ws[f'B{row}'] = f'=B{gross_wealth_row}-B{debts_row}'
    apply_calc_style(ws[f'B{row}'])
    ws[f'B{row}'].number_format = '#,##0.00'
    ws[f'B{row}'].font = Font(bold=True)
    row += 1

    ws[f'A{row}'] = 'Zürich Wealth Tax'
    wealth_tax_row = row
    wealth_cell = f'B{net_wealth_row}'
    # Zürich wealth tax formula (cantonal + municipal with 1.19 multiplier)
    wealth_tax_formula = f'''=IF({wealth_cell}<=77000,0,
IF({wealth_cell}<=308000,({wealth_cell}-77000)*0.0005*1.19,
IF({wealth_cell}<=3158000,115.50+({{wealth_cell}}-308000)*0.001*1.19,
3391.50+({wealth_cell}-3158000)*0.003*1.19)))'''

    ws[f'B{row}'] = wealth_tax_formula
    apply_result_style(ws[f'B{row}'])
    ws[f'B{row}'].number_format = '#,##0.00'
    ws[f'C{row}'] = 'Includes cantonal + municipal (1.19x)'
    ws[f'C{row}'].font = Font(italic=True, size=9)
    row += 1

    ws[f'A{row}'] = 'Wealth Tax Rate (%)'
    ws[f'B{row}'] = f'=IF(B{net_wealth_row}>0,B{wealth_tax_row}/B{net_wealth_row}*100,0)'
    apply_calc_style(ws[f'B{row}'])
    ws[f'B{row}'].number_format = '0.000"%"'
    row += 2

    # ====================
    # SECTION F: TOTAL TAX SUMMARY
    # ====================
    row = create_section_header(ws, row, "F. TOTAL TAX SUMMARY", color="FF6600")

    ws[f'A{row}'] = 'Federal Tax'
    ws[f'B{row}'] = f'=B{federal_tax_row}'
    ws[f'B{row}'].number_format = '#,##0.00'
    row += 1

    ws[f'A{row}'] = 'Cantonal Tax (Zürich)'
    ws[f'B{row}'] = f'=B{cantonal_tax_row}'
    ws[f'B{row}'].number_format = '#,##0.00'
    row += 1

    ws[f'A{row}'] = 'Municipal Tax (City Zürich)'
    ws[f'B{row}'] = f'=B{municipal_tax_row}'
    ws[f'B{row}'].number_format = '#,##0.00'
    row += 1

    ws[f'A{row}'] = 'Wealth Tax'
    ws[f'B{row}'] = f'=B{wealth_tax_row}'
    ws[f'B{row}'].number_format = '#,##0.00'
    row += 1

    ws[f'A{row}'] = '═══════════════════════════════'
    row += 1

    total_tax_row = row
    ws[f'A{row}'] = 'TOTAL ANNUAL TAX'
    ws[f'B{row}'] = f'=B{federal_tax_row}+B{cantonal_tax_row}+B{municipal_tax_row}+B{wealth_tax_row}'
    ws[f'B{row}'].fill = PatternFill(start_color="FF6600", fill_type="solid")
    ws[f'B{row}'].font = Font(bold=True, size=16, color="FFFFFF")
    ws[f'B{row}'].number_format = '#,##0.00'
    ws[f'B{row}'].alignment = Alignment(horizontal='right')
    row += 1

    ws[f'A{row}'] = 'Effective Tax Rate'
    ws[f'B{row}'] = f'=IF(B{gross_income_row}>0,B{total_tax_row}/B{gross_income_row}*100,0)'
    ws[f'B{row}'].fill = PatternFill(start_color="FFCC99", fill_type="solid")
    ws[f'B{row}'].font = Font(bold=True, size=14)
    ws[f'B{row}'].number_format = '0.00"%"'
    row += 2

    ws[f'A{row}'] = 'Net Income After Tax'
    ws[f'B{row}'] = f'=B{gross_income_row}-B{total_tax_row}'
    ws[f'B{row}'].fill = PatternFill(start_color=COLOR_RESULT, fill_type="solid")
    ws[f'B{row}'].font = Font(bold=True, size=14)
    ws[f'B{row}'].number_format = '#,##0.00'
    row += 1

    ws[f'A{row}'] = 'Monthly Net Income'
    ws[f'B{row}'] = f'=(B{gross_income_row}-B{total_tax_row})/12'
    ws[f'B{row}'].fill = PatternFill(start_color=COLOR_RESULT, fill_type="solid")
    ws[f'B{row}'].font = Font(bold=True, size=14)
    ws[f'B{row}'].number_format = '#,##0.00'
    row += 2

    # Add note about cantonal tax
    ws.merge_cells(f'A{row}:C{row}')
    ws[f'A{row}'] = 'NOTE: Cantonal tax is estimated (2.5x federal). For exact calculations, use official Zürich tax calculator.'
    ws[f'A{row}'].font = Font(italic=True, size=9, color="FF0000")
    ws[f'A{row}'].alignment = Alignment(wrap_text=True)

    # Freeze panes at title row
    ws.freeze_panes = 'A4'


def create_section_header(ws, row, title, color=COLOR_HEADER):
    """Create a section header"""
    ws.merge_cells(f'A{row}:E{row}')
    ws[f'A{row}'] = title
    ws[f'A{row}'].font = Font(bold=True, size=12, color="FFFFFF")
    ws[f'A{row}'].fill = PatternFill(start_color=color, fill_type="solid")
    ws[f'A{row}'].alignment = Alignment(horizontal='left', vertical='center')
    ws.row_dimensions[row].height = 25
    return row + 1


def apply_input_style(cell):
    """Apply input cell styling"""
    cell.fill = PatternFill(start_color=COLOR_INPUT, fill_type="solid")
    cell.font = Font(bold=True)
    cell.alignment = Alignment(horizontal='right')
    cell.number_format = '#,##0.00'


def apply_calc_style(cell):
    """Apply calculated cell styling"""
    cell.fill = PatternFill(start_color=COLOR_CALC, fill_type="solid")
    cell.alignment = Alignment(horizontal='right')


def apply_result_style(cell):
    """Apply result cell styling"""
    cell.fill = PatternFill(start_color=COLOR_RESULT, fill_type="solid")
    cell.font = Font(bold=True)
    cell.alignment = Alignment(horizontal='right')


def create_reference_sheet(ws):
    """Create the tax brackets reference sheet"""
    ws.column_dimensions['A'].width = 25
    ws.column_dimensions['B'].width = 20
    ws.column_dimensions['C'].width = 40

    row = 1
    ws[f'A{row}'] = 'TAX BRACKETS REFERENCE 2025'
    ws[f'A{row}'].font = Font(bold=True, size=14)
    row += 2

    # Federal tax brackets
    ws[f'A{row}'] = 'FEDERAL TAX BRACKETS (Article 36 DBG - Single)'
    ws[f'A{row}'].font = Font(bold=True, size=12, color="FFFFFF")
    ws[f'A{row}'].fill = PatternFill(start_color=COLOR_HEADER, fill_type="solid")
    row += 1

    brackets_federal = [
        ("CHF 0 - 15,200", "0%", "Tax-free threshold"),
        ("CHF 15,200 - 32,800", "0.77%", "Per CHF 100 over CHF 15,000"),
        ("CHF 32,800 - 42,900", "0.88%", "Per CHF 100 over CHF 32,800"),
        ("CHF 42,900 - 57,200", "2.64%", "Per CHF 100 over CHF 42,900"),
        ("CHF 57,200 - 75,300", "2.97%", "Per CHF 100 over CHF 57,200"),
        ("CHF 75,300 - 103,400", "5.94%", "Per CHF 100 over CHF 75,300"),
        ("CHF 103,400 - 134,600", "6.60%", "Per CHF 100 over CHF 103,400"),
        ("CHF 134,600 - 176,000", "8.80%", "Per CHF 100 over CHF 134,600"),
        ("CHF 176,000 - 755,200", "11.00%", "Per CHF 100 over CHF 176,000"),
        ("CHF 755,200+", "11.50%", "Maximum rate (effective)"),
    ]

    for income_range, rate, note in brackets_federal:
        ws[f'A{row}'] = income_range
        ws[f'B{row}'] = rate
        ws[f'C{row}'] = note
        ws[f'C{row}'].font = Font(italic=True, size=9)
        row += 1

    row += 2

    # Zürich wealth tax
    ws[f'A{row}'] = 'ZÜRICH WEALTH TAX (Cantonal + Municipal)'
    ws[f'A{row}'].font = Font(bold=True, size=12, color="FFFFFF")
    ws[f'A{row}'].fill = PatternFill(start_color=COLOR_HEADER, fill_type="solid")
    row += 1

    brackets_wealth = [
        ("CHF 0 - 77,000", "0%", "Tax-free (cantonal exemption)"),
        ("CHF 77,000 - 308,000", "0.05%", "0.5 CHF per 1,000 CHF × 1.19 municipal"),
        ("CHF 308,000 - 3,158,000", "0.1%", "1 CHF per 1,000 CHF × 1.19 municipal"),
        ("CHF 3,158,000+", "0.3%", "3 CHF per 1,000 CHF × 1.19 municipal"),
    ]

    for wealth_range, rate, note in brackets_wealth:
        ws[f'A{row}'] = wealth_range
        ws[f'B{row}'] = rate
        ws[f'C{row}'] = note
        ws[f'C{row}'].font = Font(italic=True, size=9)
        row += 1

    row += 2

    # Municipal multiplier
    ws[f'A{row}'] = 'City of Zürich Municipal Multiplier: 119% (1.19)'
    ws[f'A{row}'].font = Font(bold=True, size=11, color="FF6600")
    row += 2

    # Social security rates
    ws[f'A{row}'] = 'SOCIAL SECURITY CONTRIBUTIONS (2025)'
    ws[f'A{row}'].font = Font(bold=True, size=12, color="FFFFFF")
    ws[f'A{row}'].fill = PatternFill(start_color=COLOR_HEADER, fill_type="solid")
    row += 1

    ws[f'A{row}'] = 'AHV/IV/EO'
    ws[f'B{row}'] = '5.30%'
    ws[f'C{row}'] = 'Employee contribution (no salary cap)'
    row += 1

    ws[f'A{row}'] = 'Unemployment ALV'
    ws[f'B{row}'] = '1.10%'
    ws[f'C{row}'] = 'Employee contribution (up to CHF 148,200)'
    row += 1


def create_tips_sheet(ws):
    """Create the optimization tips sheet"""
    ws.column_dimensions['A'].width = 80

    row = 1
    ws[f'A{row}'] = 'TAX OPTIMIZATION TIPS FOR 2025'
    ws[f'A{row}'].font = Font(bold=True, size=14)
    row += 2

    tips = [
        ("MAXIMIZE PILLAR 3a", "Contribute the maximum CHF 7,258 before Dec 31, 2025. This is the #1 tax deduction!"),
        ("PILLAR 2 BUYBACK", "If you have gaps in your pension, consider a Pillar 2 buyback (wait 3 years before withdrawal)."),
        ("MEAL DEDUCTIONS", "Don't forget to claim CHF 15/day for meals (or CHF 7.50 if you have a subsidized canteen)."),
        ("COMMUTING COSTS", "Deduct actual public transport costs or mileage-based deductions."),
        ("HEALTH INSURANCE", "All health insurance premiums are deductible - include them!"),
        ("DONATIONS", "Charitable donations: min CHF 100, max 20% of income. Political donations: max CHF 10,600."),
        ("LOAN INTEREST", "ALL loan interest is deductible: mortgages, personal loans, credit cards."),
        ("ASSET MANAGEMENT", "Flat-rate deduction of 3‰ (0.3%) for securities portfolio management."),
        ("EXPECTED FEDERAL TAX", "Deduct expected federal tax as a debt from your wealth to reduce wealth tax."),
        ("EDUCATION COSTS", "Post-secondary education: up to CHF 13,000/year deductible."),
        ("WEALTH TAX REDUCTION", "Maximize Pillar 2/3a contributions - these assets are exempt from wealth tax!"),
        ("CAPITAL GAINS", "Hold securities 6+ months and keep trading under 5× portfolio value to keep capital gains tax-free."),
        ("DECEMBER 31 DEADLINE", "Pillar 3a and other payments must be made by Dec 31 to count for that tax year."),
        ("PROPERTY DEDUCTIONS", "Until 2028: mortgage interest and maintenance costs are deductible (Eigenmietwert reform)."),
        ("VERIFY WITH OFFICIAL CALCULATOR", "Always verify calculations with estv.admin.ch or comparis.ch tax calculator."),
    ]

    for title, description in tips:
        ws[f'A{row}'] = f"• {title}"
        ws[f'A{row}'].font = Font(bold=True, size=11, color=COLOR_HEADER)
        row += 1
        ws[f'A{row}'] = f"  {description}"
        ws[f'A{row}'].font = Font(size=10)
        ws[f'A{row}'].alignment = Alignment(wrap_text=True)
        ws.row_dimensions[row].height = 30
        row += 2

    row += 2
    ws[f'A{row}'] = 'IMPORTANT DATES'
    ws[f'A{row}'].font = Font(bold=True, size=12, color="FF0000")
    row += 1

    dates = [
        "December 31, 2025: Last day for Pillar 3a contributions",
        "December 31, 2025: Securities assessed for wealth tax",
        "March 31, 2026: Typical tax return deadline (check your canton)",
    ]

    for date in dates:
        ws[f'A{row}'] = f"• {date}"
        ws[f'A{row}'].font = Font(size=10)
        row += 1


def create_instructions_sheet(ws):
    """Create the instructions sheet"""
    ws.column_dimensions['A'].width = 90

    row = 1
    ws[f'A{row}'] = 'HOW TO USE THIS TAX CALCULATOR'
    ws[f'A{row}'].font = Font(bold=True, size=14)
    row += 2

    instructions = [
        ("STEP 1: ENTER YOUR INCOME",
         "Go to the 'Tax Calculator' sheet and enter your gross annual salary in Section A. "
         "Social security deductions (AHV/IV/EO and ALV) will be calculated automatically."),

        ("STEP 2: ENTER DEDUCTIONS",
         "In Section B, enter all your deductions:\n"
         "• Pillar 3a contributions (max CHF 7,258)\n"
         "• Health insurance premiums (actual amount)\n"
         "• Working days and meal rate for meal deductions\n"
         "• Any other applicable deductions"),

        ("STEP 3: ENTER WEALTH INFORMATION",
         "In Section E, enter your wealth as of December 31:\n"
         "• Securities/investments\n"
         "• Bank accounts and cash\n"
         "• Real estate (at tax value)\n"
         "• Debts (mortgages, loans)"),

        ("STEP 4: REVIEW RESULTS",
         "Section F shows your complete tax summary:\n"
         "• Federal, cantonal, municipal, and wealth taxes\n"
         "• Total annual tax and effective rate\n"
         "• Net income after tax"),

        ("COLOR CODING",
         "• BLUE cells: Enter your data here\n"
         "• GREEN cells: Auto-calculated (don't edit)\n"
         "• YELLOW cells: Results and summaries"),

        ("IMPORTANT NOTES",
         "• Cantonal tax is ESTIMATED (2.5× federal tax). Use official calculators for precise amounts.\n"
         "• This calculator is for CITY OF ZÜRICH only (119% municipal multiplier).\n"
         "• Always verify with official tools: estv.admin.ch or comparis.ch\n"
         "• For exact cantonal rates, consult Zürich tax authority."),

        ("SCENARIO COMPARISON",
         "To compare scenarios (e.g., with/without max Pillar 3a):\n"
         "1. Copy column B to column D\n"
         "2. Change the input values in column D\n"
         "3. Compare the results side-by-side"),

        ("SOURCES & VERIFICATION",
         "• Federal tax: Official Form 58c (ESTV)\n"
         "• Zürich wealth tax: karpeo.ch, The Poor Swiss\n"
         "• Social security rates: ESTV, UZH\n"
         "• Verify calculations: estv.admin.ch/calculator"),
    ]

    for title, description in instructions:
        ws[f'A{row}'] = title
        ws[f'A{row}'].font = Font(bold=True, size=12, color="FFFFFF")
        ws[f'A{row}'].fill = PatternFill(start_color=COLOR_HEADER, fill_type="solid")
        row += 1
        ws[f'A{row}'] = description
        ws[f'A{row}'].font = Font(size=10)
        ws[f'A{row}'].alignment = Alignment(wrap_text=True, vertical='top')
        ws.row_dimensions[row].height = 80
        row += 2

    row += 2
    ws[f'A{row}'] = 'For questions or issues, consult a Swiss tax advisor or your cantonal tax office.'
    ws[f'A{row}'].font = Font(italic=True, size=9, color="666666")


if __name__ == "__main__":
    print("=" * 60)
    print("SWISS TAX CALCULATOR GENERATOR")
    print("City of Zürich | Single Employed Person | 2025")
    print("=" * 60)
    print()
    create_tax_calculator()
    print()
    print("=" * 60)
